# Generated by Django 5.0.3 on 2024-03-27 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_itenscompra"),
    ]

    operations = [
        migrations.AddField(
            model_name="itenscompra",
            name="preco_item",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
